# Generated by Django 4.2.4 on 2023-08-19 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('code_for_link', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('chosen_date', models.DateTimeField(blank=True)),
                ('chosen_ticket_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.tickets')),
            ],
        ),
    ]
