# Generated by Django 4.2.4 on 2023-08-19 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='chosen_ticket_id',
            new_name='chosen_ticket',
        ),
    ]
