# Generated by Django 4.2.4 on 2023-08-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_rename_chosen_ticket_id_participant_chosen_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='chosen_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
