# Generated by Django 4.2.4 on 2023-08-19 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_tickets_ticket'),
        ('participants', '0003_alter_participant_chosen_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='chosen_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket'),
        ),
    ]
