# Generated by Django 4.2.4 on 2023-08-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticket_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='is_available',
            field=models.SmallIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='topic',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
