# Generated by Django 4.2.4 on 2023-08-25 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_ticket_is_available_alter_ticket_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='participant',
            new_name='participant_cfl',
        ),
    ]
